
project_id = "xndvrjgheguqysltlheg"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[[functions]]
name = "chat-llm"
verify_jwt = false

[[functions]]
name = "initiate-call"
verify_jwt = false
