
project_id = "xndvrjgheguqysltlheg"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[functions.chat-llm]
verify_jwt = false

[functions.initiate-call]
verify_jwt = false
