// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xndvrjgheguqysltlheg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuZHZyamdoZWd1cXlzbHRsaGVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2OTg2MDgsImV4cCI6MjA1ODI3NDYwOH0.opkQn5J3rSf1n5FO0Ds4pY5Lur8nrgsaGQwnHvjaLaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);